/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.clasesAuxiliares.AnimatorSwing;
import java.awt.Cursor;

/**
 *
 * @author hexal
 */
public class PrePartida extends javax.swing.JFrame {

    /**
     * Creates new form PrePartida
     */
    public PrePartida() {
        initComponents();
        botonSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AnimatorSwing.floatAnimation(configMenu, 2, 0.03);
        AnimatorSwing.floatAnimation(fondo, 6, 0.01);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        iniciarPart = new javax.swing.JButton();
        aniadirJug1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        listaJug = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        exitBo = new javax.swing.JLabel();
        jugarText = new javax.swing.JLabel();
        jugarbase = new javax.swing.JLabel();
        jugarsombra = new javax.swing.JLabel();
        canttexto = new javax.swing.JLabel();
        jugar2 = new javax.swing.JLabel();
        jugar = new javax.swing.JLabel();
        canttexto1 = new javax.swing.JLabel();
        canttexto2 = new javax.swing.JLabel();
        jugar1 = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        menuTextBase = new javax.swing.JLabel();
        menuTextShadow = new javax.swing.JLabel();
        menuText1 = new javax.swing.JLabel();
        menuTextBase1 = new javax.swing.JLabel();
        configMenu = new javax.swing.JLabel();
        configMenu1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        menuTextShadow1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1930, 1030));

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 120));

        iniciarPart.setBorderPainted(false);
        iniciarPart.setContentAreaFilled(false);
        iniciarPart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPartActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 680, 300, 110));

        aniadirJug1.setBorderPainted(false);
        aniadirJug1.setContentAreaFilled(false);
        aniadirJug1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aniadirJug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirJug1ActionPerformed(evt);
            }
        });
        jPanel1.add(aniadirJug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 120, 110));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(7, 88, 119));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 320, 70));

        jList1.setBackground(new java.awt.Color(7, 88, 119));
        jList1.setFont(new java.awt.Font("Pixeloid Sans", 1, 36)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setAutoscrolls(false);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jList1.setVisibleRowCount(4);
        listaJug.setViewportView(jList1);

        jPanel1.add(listaJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 390, 430, 200));

        exitBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/exitBtnBigger.png"))); // NOI18N
        jPanel1.add(exitBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 110));

        jugarText.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        jugarText.setForeground(new java.awt.Color(255, 255, 255));
        jugarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarText.setText("JUGAR");
        jPanel1.add(jugarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 700, 200, 70));

        jugarbase.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        jugarbase.setForeground(new java.awt.Color(0, 204, 204));
        jugarbase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase.setText("JUGAR");
        jPanel1.add(jugarbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 690, 200, 90));

        jugarsombra.setFont(new java.awt.Font("Pixeloid Sans", 0, 50)); // NOI18N
        jugarsombra.setForeground(new java.awt.Color(30, 126, 126));
        jugarsombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra.setText("JUGAR");
        jPanel1.add(jugarsombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, 250, 80));

        canttexto.setFont(new java.awt.Font("Pixeloid Sans", 0, 170)); // NOI18N
        canttexto.setForeground(new java.awt.Color(255, 255, 255));
        canttexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canttexto.setText("+");
        jPanel1.add(canttexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 300, 160, 130));

        jugar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 410, 310));

        jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/jugarBtn.png"))); // NOI18N
        jPanel1.add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 130, 120));

        canttexto1.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        canttexto1.setForeground(new java.awt.Color(255, 255, 255));
        canttexto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canttexto1.setText("añadir jug");
        jPanel1.add(canttexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 430, 130));

        canttexto2.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        canttexto2.setForeground(new java.awt.Color(102, 102, 102));
        canttexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canttexto2.setText("añadir jug");
        jPanel1.add(canttexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 430, 130));

        jugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 730, 170));

        menuText.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText.setText("CONFIG");
        jPanel1.add(menuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 800, 190));

        menuTextBase.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuTextBase.setForeground(new java.awt.Color(153, 153, 153));
        menuTextBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextBase.setText("CONFIG");
        jPanel1.add(menuTextBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 800, 260));

        menuTextShadow.setFont(new java.awt.Font("Pixeloid Sans", 0, 74)); // NOI18N
        menuTextShadow.setForeground(new java.awt.Color(59, 113, 118));
        menuTextShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextShadow.setText("CONFIG");
        jPanel1.add(menuTextShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 930, 270));

        menuText1.setFont(new java.awt.Font("Pixeloid Sans", 0, 50)); // NOI18N
        menuText1.setForeground(new java.awt.Color(255, 255, 255));
        menuText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText1.setText("JUGADORES");
        jPanel1.add(menuText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 800, 190));

        menuTextBase1.setFont(new java.awt.Font("Pixeloid Sans", 0, 50)); // NOI18N
        menuTextBase1.setForeground(new java.awt.Color(153, 153, 153));
        menuTextBase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextBase1.setText("JUGADORES");
        jPanel1.add(menuTextBase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 800, 260));

        configMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        configMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/MenuSmall.png"))); // NOI18N
        jPanel1.add(configMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 1240, 530));

        configMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        configMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/17 nov 2025, 09_48_56.png"))); // NOI18N
        jPanel1.add(configMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 1410, 880));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Desenfocado.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1920, 1080));

        menuTextShadow1.setFont(new java.awt.Font("Pixeloid Sans", 0, 74)); // NOI18N
        menuTextShadow1.setForeground(new java.awt.Color(59, 113, 118));
        menuTextShadow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextShadow1.setText("CONFIG");
        jPanel1.add(menuTextShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 930, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        Menu entrada = new Menu();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void iniciarPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarPartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarPartActionPerformed

    private void aniadirJug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirJug1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aniadirJug1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrePartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aniadirJug1;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel canttexto;
    private javax.swing.JLabel canttexto1;
    private javax.swing.JLabel canttexto2;
    private javax.swing.JLabel configMenu;
    private javax.swing.JLabel configMenu1;
    private javax.swing.JLabel exitBo;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciarPart;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jugar;
    private javax.swing.JLabel jugar1;
    private javax.swing.JLabel jugar2;
    private javax.swing.JLabel jugarText;
    private javax.swing.JLabel jugarbase;
    private javax.swing.JLabel jugarsombra;
    private javax.swing.JScrollPane listaJug;
    private javax.swing.JLabel menuText;
    private javax.swing.JLabel menuText1;
    private javax.swing.JLabel menuTextBase;
    private javax.swing.JLabel menuTextBase1;
    private javax.swing.JLabel menuTextShadow;
    private javax.swing.JLabel menuTextShadow1;
    // End of variables declaration//GEN-END:variables
}
