/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.clasesAuxiliares.AnimatorSwing;
import java.awt.Cursor;

/**
 *
 * @author hexal
 */
public class PrePartida extends javax.swing.JFrame {

    /**
     * Creates new form PrePartida
     */
    public PrePartida() {
        initComponents();
        botonSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        AnimatorSwing.floatAnimation(configMenu, 2, 0.03);
        AnimatorSwing.floatAnimation(fondo, 6, 0.01);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        exitBo = new javax.swing.JLabel();
        jugarText = new javax.swing.JLabel();
        jugarbase = new javax.swing.JLabel();
        jugarsombra = new javax.swing.JLabel();
        jugar = new javax.swing.JLabel();
        menuText2 = new javax.swing.JLabel();
        menuText1 = new javax.swing.JLabel();
        menuText = new javax.swing.JLabel();
        menuTextBase = new javax.swing.JLabel();
        menuTextShadow = new javax.swing.JLabel();
        configMenu = new javax.swing.JLabel();
        configMenu1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        menuTextShadow1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1930, 1030));

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 120));

        exitBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/exitBtnBigger.png"))); // NOI18N
        jPanel1.add(exitBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 110));

        jugarText.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        jugarText.setForeground(new java.awt.Color(255, 255, 255));
        jugarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarText.setText("JUGAR");
        jPanel1.add(jugarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 700, 200, 70));

        jugarbase.setFont(new java.awt.Font("Pixeloid Sans", 0, 48)); // NOI18N
        jugarbase.setForeground(new java.awt.Color(0, 204, 204));
        jugarbase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarbase.setText("JUGAR");
        jPanel1.add(jugarbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 690, 200, 90));

        jugarsombra.setFont(new java.awt.Font("Pixeloid Sans", 0, 50)); // NOI18N
        jugarsombra.setForeground(new java.awt.Color(30, 126, 126));
        jugarsombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jugarsombra.setText("JUGAR");
        jPanel1.add(jugarsombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, 250, 80));

        jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Jugaf2.png"))); // NOI18N
        jPanel1.add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 730, 170));

        menuText2.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuText2.setForeground(new java.awt.Color(255, 255, 255));
        menuText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText2.setText("Cant Jug");
        jPanel1.add(menuText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 430, 130));

        menuText1.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuText1.setForeground(new java.awt.Color(102, 102, 102));
        menuText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText1.setText("Cant Jug");
        jPanel1.add(menuText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 315, 430, 130));

        menuText.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuText.setForeground(new java.awt.Color(255, 255, 255));
        menuText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuText.setText("CONFIG");
        jPanel1.add(menuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 800, 190));

        menuTextBase.setFont(new java.awt.Font("Pixeloid Sans", 0, 70)); // NOI18N
        menuTextBase.setForeground(new java.awt.Color(153, 153, 153));
        menuTextBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextBase.setText("CONFIG");
        jPanel1.add(menuTextBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 800, 260));

        menuTextShadow.setFont(new java.awt.Font("Pixeloid Sans", 0, 74)); // NOI18N
        menuTextShadow.setForeground(new java.awt.Color(59, 113, 118));
        menuTextShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextShadow.setText("CONFIG");
        jPanel1.add(menuTextShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 930, 270));

        configMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        configMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/MenuSmall.png"))); // NOI18N
        jPanel1.add(configMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -50, 1410, 880));

        configMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        configMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/17 nov 2025, 09_48_56.png"))); // NOI18N
        jPanel1.add(configMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 1410, 880));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/recursos/Desenfocado.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1920, 1080));

        menuTextShadow1.setFont(new java.awt.Font("Pixeloid Sans", 0, 74)); // NOI18N
        menuTextShadow1.setForeground(new java.awt.Color(59, 113, 118));
        menuTextShadow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTextShadow1.setText("CONFIG");
        jPanel1.add(menuTextShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 930, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        Menu entrada = new Menu();
        entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrePartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrePartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel configMenu;
    private javax.swing.JLabel configMenu1;
    private javax.swing.JLabel exitBo;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jugar;
    private javax.swing.JLabel jugarText;
    private javax.swing.JLabel jugarbase;
    private javax.swing.JLabel jugarsombra;
    private javax.swing.JLabel menuText;
    private javax.swing.JLabel menuText1;
    private javax.swing.JLabel menuText2;
    private javax.swing.JLabel menuTextBase;
    private javax.swing.JLabel menuTextShadow;
    private javax.swing.JLabel menuTextShadow1;
    // End of variables declaration//GEN-END:variables
}
